// Mock data for demonstration purposes
// Replace with actual backend API calls in production

export const mockStudents = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@university.edu',
    student_id: 'STU001',
    department: 'Computer Science',
    semester: 4,
    gpa: 2.8,
    attendance: 72,
    risk_level: 'high' as const,
    dropout_probability: 0.68,
  },
  {
    id: '2',
    name: 'Marcus Chen',
    email: 'marcus.chen@university.edu',
    student_id: 'STU002',
    department: 'Business',
    semester: 3,
    gpa: 3.2,
    attendance: 85,
    risk_level: 'medium' as const,
    dropout_probability: 0.32,
  },
  {
    id: '3',
    name: 'Emma Rodriguez',
    email: 'emma.rodriguez@university.edu',
    student_id: 'STU003',
    department: 'Engineering',
    semester: 2,
    gpa: 3.8,
    attendance: 95,
    risk_level: 'low' as const,
    dropout_probability: 0.05,
  },
  {
    id: '4',
    name: 'James Williams',
    email: 'james.williams@university.edu',
    student_id: 'STU004',
    department: 'Computer Science',
    semester: 3,
    gpa: 2.5,
    attendance: 68,
    risk_level: 'high' as const,
    dropout_probability: 0.75,
  },
  {
    id: '5',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@university.edu',
    student_id: 'STU005',
    department: 'Biology',
    semester: 4,
    gpa: 3.5,
    attendance: 90,
    risk_level: 'low' as const,
    dropout_probability: 0.08,
  },
  {
    id: '6',
    name: 'David Kim',
    email: 'david.kim@university.edu',
    student_id: 'STU006',
    department: 'Mathematics',
    semester: 2,
    gpa: 2.9,
    attendance: 78,
    risk_level: 'medium' as const,
    dropout_probability: 0.42,
  },
]

export const mockStudentDetail = {
  id: '1',
  name: 'Sarah Johnson',
  email: 'sarah.johnson@university.edu',
  student_id: 'STU001',
  department: 'Computer Science',
  semester: 4,
  gpa: 2.8,
  attendance: 72,
  risk_level: 'high' as const,
  dropout_probability: 0.68,
  attendance_trend: [
    { week: 1, percentage: 92 },
    { week: 2, percentage: 88 },
    { week: 3, percentage: 85 },
    { week: 4, percentage: 80 },
    { week: 5, percentage: 75 },
    { week: 6, percentage: 72 },
    { week: 7, percentage: 68 },
    { week: 8, percentage: 72 },
  ],
  score_trend: [
    { exam: 'Midterm 1', score: 68 },
    { exam: 'Quiz 1', score: 62 },
    { exam: 'Midterm 2', score: 65 },
    { exam: 'Quiz 2', score: 58 },
    { exam: 'Assignment 1', score: 70 },
  ],
  risk_factors: [
    'Declining attendance pattern',
    'Below 2.9 GPA threshold',
    'Recent exam score decline',
    'Limited engagement in coursework',
    'Missing multiple assignment deadlines',
  ],
  recommendations: [
    'Schedule one-on-one meeting with academic advisor',
    'Recommend tutoring sessions for core subjects',
    'Consider peer study group participation',
    'Discuss personal challenges affecting performance',
    'Explore additional support services',
  ],
}

export const mockDashboardStats = {
  total_students: 342,
  high_risk_count: 28,
  medium_risk_count: 45,
  low_risk_count: 269,
  avg_dropout_probability: 0.12,
}
